//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AbstractLatLonBoxType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;AbstractLatLonBoxType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractObjectType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}north&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}south&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}east&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}west&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractLatLonBoxType", propOrder = { "north", "south",
		"east", "west" })
@XmlSeeAlso( { LatLonBoxType.class, LatLonAltBoxType.class })
public abstract class AbstractLatLonBoxType extends AbstractObjectType
		implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5247386875592571294L;
	@XmlElement(defaultValue = "180.0")
	protected Double north;
	@XmlElement(defaultValue = "-180.0")
	protected Double south;
	@XmlElement(defaultValue = "180.0")
	protected Double east;
	@XmlElement(defaultValue = "-180.0")
	protected Double west;

	/**
	 * Gets the value of the north property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getNorth() {
		return north;
	}

	/**
	 * Sets the value of the north property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setNorth(Double value) {
		this.north = value;
	}

	/**
	 * Gets the value of the south property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getSouth() {
		return south;
	}

	/**
	 * Sets the value of the south property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setSouth(Double value) {
		this.south = value;
	}

	/**
	 * Gets the value of the east property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getEast() {
		return east;
	}

	/**
	 * Sets the value of the east property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setEast(Double value) {
		this.east = value;
	}

	/**
	 * Gets the value of the west property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getWest() {
		return west;
	}

	/**
	 * Sets the value of the west property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setWest(Double value) {
		this.west = value;
	}

}
