//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for BalloonStyleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;BalloonStyleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractSubStyleType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}color&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}bgColor&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}textColor&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}text&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}displayMode&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BalloonStyleType", propOrder = { "color", "bgColor",
		"textColor", "text", "displayMode" })
public class BalloonStyleType extends AbstractSubStyleType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1831257866797599733L;
	@XmlElement(type = String.class, defaultValue = "ffffffff")
	@XmlJavaTypeAdapter(HexBinaryAdapter.class)
	protected byte[] color;
	@XmlElement(type = String.class, defaultValue = "ffffffff")
	@XmlJavaTypeAdapter(HexBinaryAdapter.class)
	protected byte[] bgColor;
	@XmlElement(type = String.class, defaultValue = "ff000000")
	@XmlJavaTypeAdapter(HexBinaryAdapter.class)
	protected byte[] textColor;
	protected String text;
	@XmlElement(defaultValue = "default")
	protected DisplayModeEnumType displayMode;

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public byte[] getColor() {
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(byte[] value) {
		this.color = (value);
	}

	/**
	 * Gets the value of the bgColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public byte[] getBgColor() {
		return bgColor;
	}

	/**
	 * Sets the value of the bgColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBgColor(byte[] value) {
		this.bgColor = (value);
	}

	/**
	 * Gets the value of the textColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public byte[] getTextColor() {
		return textColor;
	}

	/**
	 * Sets the value of the textColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextColor(byte[] value) {
		this.textColor = (value);
	}

	/**
	 * Gets the value of the text property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getText() {
		return text;
	}

	/**
	 * Sets the value of the text property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setText(String value) {
		this.text = value;
	}

	/**
	 * Gets the value of the displayMode property.
	 * 
	 * @return possible object is {@link DisplayModeEnumType }
	 * 
	 */
	public DisplayModeEnumType getDisplayMode() {
		return displayMode;
	}

	/**
	 * Sets the value of the displayMode property.
	 * 
	 * @param value
	 *            allowed object is {@link DisplayModeEnumType }
	 * 
	 */
	public void setDisplayMode(DisplayModeEnumType value) {
		this.displayMode = value;
	}

}
