//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BoundaryType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;BoundaryType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}LinearRing&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundaryType", propOrder = { "linearRing" })
public class BoundaryType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7822550065637748852L;
	@XmlElement(name = "LinearRing")
	protected LinearRingType linearRing;

	/**
	 * Gets the value of the linearRing property.
	 * 
	 * @return possible object is {@link LinearRingType }
	 * 
	 */
	public LinearRingType getLinearRing() {
		return linearRing;
	}

	/**
	 * Sets the value of the linearRing property.
	 * 
	 * @param value
	 *            allowed object is {@link LinearRingType }
	 * 
	 */
	public void setLinearRing(LinearRingType value) {
		this.linearRing = value;
	}

}
