//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DocumentType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;DocumentType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractContainerType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Schema&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}AbstractFeatureGroup&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentType", propOrder = { "schema", "abstractFeatureGroup" })
public class DocumentType extends AbstractContainerType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6063443651687738417L;
	@XmlElement(name = "Schema")
	protected List<SchemaType> schema;
	@XmlElementRef(name = "AbstractFeatureGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected List<JAXBElement<? extends AbstractFeatureType>> abstractFeatureGroup;

	/**
	 * Gets the value of the schema property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the schema property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSchema().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SchemaType }
	 * 
	 * 
	 */
	public List<SchemaType> getSchema() {
		if (schema == null) {
			schema = new ArrayList<SchemaType>();
		}
		return this.schema;
	}

	/**
	 * Gets the value of the abstractFeatureGroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the abstractFeatureGroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAbstractFeatureGroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link AbstractOverlayType }{@code >}
	 * {@link JAXBElement }{@code <}{@link PlacemarkType }{@code >}
	 * {@link JAXBElement }{@code <}{@link AbstractContainerType }{@code >}
	 * {@link JAXBElement }{@code <}{@link PhotoOverlayType }{@code >}
	 * {@link JAXBElement }{@code <}{@link DocumentType }{@code >}
	 * {@link JAXBElement }{@code <}{@link AbstractFeatureType }{@code >}
	 * {@link JAXBElement }{@code <}{@link FolderType }{@code >}
	 * {@link JAXBElement }{@code <}{@link ScreenOverlayType }{@code >}
	 * {@link JAXBElement }{@code <}{@link GroundOverlayType }{@code >}
	 * {@link JAXBElement }{@code <}{@link NetworkLinkType }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<? extends AbstractFeatureType>> getAbstractFeatureGroup() {
		if (abstractFeatureGroup == null) {
			abstractFeatureGroup = new ArrayList<JAXBElement<? extends AbstractFeatureType>>();
		}
		return this.abstractFeatureGroup;
	}

}
