//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for GroundOverlayType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;GroundOverlayType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractOverlayType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}altitude&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}altitudeModeGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}LatLonBox&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroundOverlayType", propOrder = { "altitude",
		"altitudeModeGroup", "latLonBox" })
public class GroundOverlayType extends AbstractOverlayType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 320085273529450801L;
	@XmlElement(defaultValue = "0.0")
	protected Double altitude;
	@XmlElementRef(name = "altitudeModeGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<?> altitudeModeGroup;
	@XmlElement(name = "LatLonBox")
	protected LatLonBoxType latLonBox;

	/**
	 * Gets the value of the altitude property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getAltitude() {
		return altitude;
	}

	/**
	 * Sets the value of the altitude property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setAltitude(Double value) {
		this.altitude = value;
	}

	/**
	 * Gets the value of the altitudeModeGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link Object }
	 *         {@code >} {@link JAXBElement }{@code <}
	 *         {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public JAXBElement<?> getAltitudeModeGroup() {
		return altitudeModeGroup;
	}

	/**
	 * Sets the value of the altitudeModeGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Object }
	 *            {@code >} {@link JAXBElement }{@code <}
	 *            {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public void setAltitudeModeGroup(JAXBElement<?> value) {
		this.altitudeModeGroup = (value);
	}

	/**
	 * Gets the value of the latLonBox property.
	 * 
	 * @return possible object is {@link LatLonBoxType }
	 * 
	 */
	public LatLonBoxType getLatLonBox() {
		return latLonBox;
	}

	/**
	 * Sets the value of the latLonBox property.
	 * 
	 * @param value
	 *            allowed object is {@link LatLonBoxType }
	 * 
	 */
	public void setLatLonBox(LatLonBoxType value) {
		this.latLonBox = value;
	}

}
