//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for IconStyleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;IconStyleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractColorStyleType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}scale&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}heading&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;Icon&quot; type=&quot;{http://earth.google.com/kml/2.2}BasicLinkType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}hotSpot&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IconStyleType", propOrder = { "scale", "heading", "icon",
		"hotSpot" })
public class IconStyleType extends AbstractColorStyleType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1181348047414835546L;
	@XmlElement(defaultValue = "1.0")
	protected Double scale;
	@XmlElement(defaultValue = "0.0")
	protected Double heading;
	@XmlElement(name = "Icon")
	protected BasicLinkType icon;
	protected Vec2Type hotSpot;

	/**
	 * Gets the value of the scale property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getScale() {
		return scale;
	}

	/**
	 * Sets the value of the scale property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setScale(Double value) {
		this.scale = value;
	}

	/**
	 * Gets the value of the heading property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getHeading() {
		return heading;
	}

	/**
	 * Sets the value of the heading property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setHeading(Double value) {
		this.heading = value;
	}

	/**
	 * Gets the value of the icon property.
	 * 
	 * @return possible object is {@link BasicLinkType }
	 * 
	 */
	public BasicLinkType getIcon() {
		return icon;
	}

	/**
	 * Sets the value of the icon property.
	 * 
	 * @param value
	 *            allowed object is {@link BasicLinkType }
	 * 
	 */
	public void setIcon(BasicLinkType value) {
		this.icon = value;
	}

	/**
	 * Gets the value of the hotSpot property.
	 * 
	 * @return possible object is {@link Vec2Type }
	 * 
	 */
	public Vec2Type getHotSpot() {
		return hotSpot;
	}

	/**
	 * Sets the value of the hotSpot property.
	 * 
	 * @param value
	 *            allowed object is {@link Vec2Type }
	 * 
	 */
	public void setHotSpot(Vec2Type value) {
		this.hotSpot = value;
	}

}
