//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for itemIconStateEnumType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;itemIconStateEnumType&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;open&quot;/&gt;
 *     &lt;enumeration value=&quot;closed&quot;/&gt;
 *     &lt;enumeration value=&quot;error&quot;/&gt;
 *     &lt;enumeration value=&quot;fetching0&quot;/&gt;
 *     &lt;enumeration value=&quot;fetching1&quot;/&gt;
 *     &lt;enumeration value=&quot;fetching2&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "itemIconStateEnumType")
@XmlEnum
public enum ItemIconStateEnumType implements java.io.Serializable {

	@XmlEnumValue("open")
	OPEN("open"), @XmlEnumValue("closed")
	CLOSED("closed"), @XmlEnumValue("error")
	ERROR("error"), @XmlEnumValue("fetching0")
	FETCHING_0("fetching0"), @XmlEnumValue("fetching1")
	FETCHING_1("fetching1"), @XmlEnumValue("fetching2")
	FETCHING_2("fetching2");
	private final String value;

	ItemIconStateEnumType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static ItemIconStateEnumType fromValue(String v) {
		for (ItemIconStateEnumType c : ItemIconStateEnumType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
