//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for KmlType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;KmlType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}NetworkLinkControl&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}AbstractFeatureGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;hint&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KmlType", propOrder = { "networkLinkControl",
		"abstractFeatureGroup" })
public class KmlType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7361634039818974500L;
	@XmlElement(name = "NetworkLinkControl")
	protected NetworkLinkControlType networkLinkControl;
	@XmlElementRef(name = "AbstractFeatureGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<? extends AbstractFeatureType> abstractFeatureGroup;
	@XmlAttribute
	protected String hint;

	/**
	 * Gets the value of the networkLinkControl property.
	 * 
	 * @return possible object is {@link NetworkLinkControlType }
	 * 
	 */
	public NetworkLinkControlType getNetworkLinkControl() {
		return networkLinkControl;
	}

	/**
	 * Sets the value of the networkLinkControl property.
	 * 
	 * @param value
	 *            allowed object is {@link NetworkLinkControlType }
	 * 
	 */
	public void setNetworkLinkControl(NetworkLinkControlType value) {
		this.networkLinkControl = value;
	}

	/**
	 * Gets the value of the abstractFeatureGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}
	 *         {@link AbstractOverlayType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link PlacemarkType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link AbstractContainerType }{@code >} {@link JAXBElement }{@code
	 *         <}{@link PhotoOverlayType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link DocumentType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link AbstractFeatureType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link FolderType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link ScreenOverlayType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link GroundOverlayType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link NetworkLinkType }{@code >}
	 * 
	 */
	public JAXBElement<? extends AbstractFeatureType> getAbstractFeatureGroup() {
		return abstractFeatureGroup;
	}

	/**
	 * Sets the value of the abstractFeatureGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}
	 *            {@link AbstractOverlayType }{@code >} {@link JAXBElement }
	 *            {@code <}{@link PlacemarkType }{@code >} {@link JAXBElement }
	 *            {@code <}{@link AbstractContainerType }{@code >}
	 *            {@link JAXBElement }{@code <}{@link PhotoOverlayType }{@code >}
	 *            {@link JAXBElement }{@code <}{@link DocumentType }{@code >}
	 *            {@link JAXBElement }{@code <}{@link AbstractFeatureType }{@code
	 *            >} {@link JAXBElement }{@code <}{@link FolderType }{@code >}
	 *            {@link JAXBElement }{@code <}{@link ScreenOverlayType }{@code >}
	 *            {@link JAXBElement }{@code <}{@link GroundOverlayType }{@code >}
	 *            {@link JAXBElement }{@code <}{@link NetworkLinkType }{@code >}
	 * 
	 */
	public void setAbstractFeatureGroup(
			JAXBElement<? extends AbstractFeatureType> value) {
		this.abstractFeatureGroup = (value);
	}

	/**
	 * Gets the value of the hint property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHint() {
		return hint;
	}

	/**
	 * Sets the value of the hint property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHint(String value) {
		this.hint = value;
	}

}
