//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LatLonAltBoxType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;LatLonAltBoxType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractLatLonBoxType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}minAltitude&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}maxAltitude&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}altitudeModeGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LatLonAltBoxType", propOrder = { "minAltitude", "maxAltitude",
		"altitudeModeGroup" })
public class LatLonAltBoxType extends AbstractLatLonBoxType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6118159929275510592L;
	@XmlElement(defaultValue = "0.0")
	protected Double minAltitude;
	@XmlElement(defaultValue = "0.0")
	protected Double maxAltitude;
	@XmlElementRef(name = "altitudeModeGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<?> altitudeModeGroup;

	/**
	 * Gets the value of the minAltitude property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getMinAltitude() {
		return minAltitude;
	}

	/**
	 * Sets the value of the minAltitude property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setMinAltitude(Double value) {
		this.minAltitude = value;
	}

	/**
	 * Gets the value of the maxAltitude property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getMaxAltitude() {
		return maxAltitude;
	}

	/**
	 * Sets the value of the maxAltitude property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setMaxAltitude(Double value) {
		this.maxAltitude = value;
	}

	/**
	 * Gets the value of the altitudeModeGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link Object }
	 *         {@code >} {@link JAXBElement }{@code <}
	 *         {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public JAXBElement<?> getAltitudeModeGroup() {
		return altitudeModeGroup;
	}

	/**
	 * Sets the value of the altitudeModeGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Object }
	 *            {@code >} {@link JAXBElement }{@code <}
	 *            {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public void setAltitudeModeGroup(JAXBElement<?> value) {
		this.altitudeModeGroup = (value);
	}

}
