//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LinkType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;LinkType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}BasicLinkType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}refreshMode&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}refreshInterval&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}viewRefreshMode&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}viewRefreshTime&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}viewBoundScale&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}viewFormat&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}httpQuery&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinkType", propOrder = { "refreshMode", "refreshInterval",
		"viewRefreshMode", "viewRefreshTime", "viewBoundScale", "viewFormat",
		"httpQuery" })
public class LinkType extends BasicLinkType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3402071288164924925L;
	@XmlElement(defaultValue = "onChange")
	protected RefreshModeEnumType refreshMode;
	@XmlElement(defaultValue = "4.0")
	protected Double refreshInterval;
	@XmlElement(defaultValue = "never")
	protected ViewRefreshModeEnumType viewRefreshMode;
	@XmlElement(defaultValue = "4.0")
	protected Double viewRefreshTime;
	@XmlElement(defaultValue = "1.0")
	protected Double viewBoundScale;
	protected String viewFormat;
	protected String httpQuery;

	/**
	 * Gets the value of the refreshMode property.
	 * 
	 * @return possible object is {@link RefreshModeEnumType }
	 * 
	 */
	public RefreshModeEnumType getRefreshMode() {
		return refreshMode;
	}

	/**
	 * Sets the value of the refreshMode property.
	 * 
	 * @param value
	 *            allowed object is {@link RefreshModeEnumType }
	 * 
	 */
	public void setRefreshMode(RefreshModeEnumType value) {
		this.refreshMode = value;
	}

	/**
	 * Gets the value of the refreshInterval property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getRefreshInterval() {
		return refreshInterval;
	}

	/**
	 * Sets the value of the refreshInterval property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setRefreshInterval(Double value) {
		this.refreshInterval = value;
	}

	/**
	 * Gets the value of the viewRefreshMode property.
	 * 
	 * @return possible object is {@link ViewRefreshModeEnumType }
	 * 
	 */
	public ViewRefreshModeEnumType getViewRefreshMode() {
		return viewRefreshMode;
	}

	/**
	 * Sets the value of the viewRefreshMode property.
	 * 
	 * @param value
	 *            allowed object is {@link ViewRefreshModeEnumType }
	 * 
	 */
	public void setViewRefreshMode(ViewRefreshModeEnumType value) {
		this.viewRefreshMode = value;
	}

	/**
	 * Gets the value of the viewRefreshTime property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getViewRefreshTime() {
		return viewRefreshTime;
	}

	/**
	 * Sets the value of the viewRefreshTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setViewRefreshTime(Double value) {
		this.viewRefreshTime = value;
	}

	/**
	 * Gets the value of the viewBoundScale property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getViewBoundScale() {
		return viewBoundScale;
	}

	/**
	 * Sets the value of the viewBoundScale property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setViewBoundScale(Double value) {
		this.viewBoundScale = value;
	}

	/**
	 * Gets the value of the viewFormat property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getViewFormat() {
		return viewFormat;
	}

	/**
	 * Sets the value of the viewFormat property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setViewFormat(String value) {
		this.viewFormat = value;
	}

	/**
	 * Gets the value of the httpQuery property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHttpQuery() {
		return httpQuery;
	}

	/**
	 * Sets the value of the httpQuery property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHttpQuery(String value) {
		this.httpQuery = value;
	}

}
