//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for ListStyleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ListStyleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractSubStyleType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}listItemType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}bgColor&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}ItemIcon&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListStyleType", propOrder = { "listItemType", "bgColor",
		"itemIcon" })
public class ListStyleType extends AbstractSubStyleType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1103978219406697798L;
	@XmlElement(defaultValue = "check")
	protected ListItemTypeEnumType listItemType;
	@XmlElement(type = String.class, defaultValue = "ffffffff")
	@XmlJavaTypeAdapter(HexBinaryAdapter.class)
	protected byte[] bgColor;
	@XmlElement(name = "ItemIcon")
	protected List<ItemIconType> itemIcon;

	/**
	 * Gets the value of the listItemType property.
	 * 
	 * @return possible object is {@link ListItemTypeEnumType }
	 * 
	 */
	public ListItemTypeEnumType getListItemType() {
		return listItemType;
	}

	/**
	 * Sets the value of the listItemType property.
	 * 
	 * @param value
	 *            allowed object is {@link ListItemTypeEnumType }
	 * 
	 */
	public void setListItemType(ListItemTypeEnumType value) {
		this.listItemType = value;
	}

	/**
	 * Gets the value of the bgColor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public byte[] getBgColor() {
		return bgColor;
	}

	/**
	 * Sets the value of the bgColor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBgColor(byte[] value) {
		this.bgColor = (value);
	}

	/**
	 * Gets the value of the itemIcon property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the itemIcon property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getItemIcon().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ItemIconType }
	 * 
	 * 
	 */
	public List<ItemIconType> getItemIcon() {
		if (itemIcon == null) {
			itemIcon = new ArrayList<ItemIconType>();
		}
		return this.itemIcon;
	}

}
