//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LodType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;LodType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractObjectType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}minLodPixels&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}maxLodPixels&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}minFadeExtent&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}maxFadeExtent&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LodType", propOrder = { "minLodPixels", "maxLodPixels",
		"minFadeExtent", "maxFadeExtent" })
public class LodType extends AbstractObjectType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8152848135219433677L;
	@XmlElement(defaultValue = "0.0")
	protected Double minLodPixels;
	@XmlElement(defaultValue = "-1.0")
	protected Double maxLodPixels;
	@XmlElement(defaultValue = "0.0")
	protected Double minFadeExtent;
	@XmlElement(defaultValue = "0.0")
	protected Double maxFadeExtent;

	/**
	 * Gets the value of the minLodPixels property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getMinLodPixels() {
		return minLodPixels;
	}

	/**
	 * Sets the value of the minLodPixels property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setMinLodPixels(Double value) {
		this.minLodPixels = value;
	}

	/**
	 * Gets the value of the maxLodPixels property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getMaxLodPixels() {
		return maxLodPixels;
	}

	/**
	 * Sets the value of the maxLodPixels property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setMaxLodPixels(Double value) {
		this.maxLodPixels = value;
	}

	/**
	 * Gets the value of the minFadeExtent property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getMinFadeExtent() {
		return minFadeExtent;
	}

	/**
	 * Sets the value of the minFadeExtent property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setMinFadeExtent(Double value) {
		this.minFadeExtent = value;
	}

	/**
	 * Gets the value of the maxFadeExtent property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getMaxFadeExtent() {
		return maxFadeExtent;
	}

	/**
	 * Sets the value of the maxFadeExtent property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setMaxFadeExtent(Double value) {
		this.maxFadeExtent = value;
	}

}
