//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ModelType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ModelType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractGeometryType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}altitudeModeGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Location&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Orientation&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Scale&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Link&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}ResourceMap&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelType", propOrder = { "altitudeModeGroup", "location",
		"orientation", "scaleA", "link", "resourceMap" })
public class ModelType extends AbstractGeometryType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7645603847975606160L;
	@XmlElementRef(name = "altitudeModeGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<?> altitudeModeGroup;
	@XmlElement(name = "Location")
	protected LocationType location;
	@XmlElement(name = "Orientation")
	protected OrientationType orientation;
	@XmlElement(name = "Scale")
	protected ScaleType scaleA;
	@XmlElement(name = "Link")
	protected LinkType link;
	@XmlElement(name = "ResourceMap")
	protected ResourceMapType resourceMap;

	/**
	 * Gets the value of the altitudeModeGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link Object }
	 *         {@code >} {@link JAXBElement }{@code <}
	 *         {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public JAXBElement<?> getAltitudeModeGroup() {
		return altitudeModeGroup;
	}

	/**
	 * Sets the value of the altitudeModeGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Object }
	 *            {@code >} {@link JAXBElement }{@code <}
	 *            {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public void setAltitudeModeGroup(JAXBElement<?> value) {
		this.altitudeModeGroup = (value);
	}

	/**
	 * Gets the value of the location property.
	 * 
	 * @return possible object is {@link LocationType }
	 * 
	 */
	public LocationType getLocation() {
		return location;
	}

	/**
	 * Sets the value of the location property.
	 * 
	 * @param value
	 *            allowed object is {@link LocationType }
	 * 
	 */
	public void setLocation(LocationType value) {
		this.location = value;
	}

	/**
	 * Gets the value of the orientation property.
	 * 
	 * @return possible object is {@link OrientationType }
	 * 
	 */
	public OrientationType getOrientation() {
		return orientation;
	}

	/**
	 * Sets the value of the orientation property.
	 * 
	 * @param value
	 *            allowed object is {@link OrientationType }
	 * 
	 */
	public void setOrientation(OrientationType value) {
		this.orientation = value;
	}

	/**
	 * Gets the value of the scaleA property.
	 * 
	 * @return possible object is {@link ScaleType }
	 * 
	 */
	public ScaleType getScaleA() {
		return scaleA;
	}

	/**
	 * Sets the value of the scaleA property.
	 * 
	 * @param value
	 *            allowed object is {@link ScaleType }
	 * 
	 */
	public void setScaleA(ScaleType value) {
		this.scaleA = value;
	}

	/**
	 * Gets the value of the link property.
	 * 
	 * @return possible object is {@link LinkType }
	 * 
	 */
	public LinkType getLink() {
		return link;
	}

	/**
	 * Sets the value of the link property.
	 * 
	 * @param value
	 *            allowed object is {@link LinkType }
	 * 
	 */
	public void setLink(LinkType value) {
		this.link = value;
	}

	/**
	 * Gets the value of the resourceMap property.
	 * 
	 * @return possible object is {@link ResourceMapType }
	 * 
	 */
	public ResourceMapType getResourceMap() {
		return resourceMap;
	}

	/**
	 * Sets the value of the resourceMap property.
	 * 
	 * @param value
	 *            allowed object is {@link ResourceMapType }
	 * 
	 */
	public void setResourceMap(ResourceMapType value) {
		this.resourceMap = value;
	}

}
