//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PairType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;PairType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractObjectType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}key&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}styleUrl&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}AbstractStyleSelectorGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PairType", propOrder = { "key", "styleUrl",
		"abstractStyleSelectorGroup" })
public class PairType extends AbstractObjectType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8112482060607408125L;
	@XmlElement(defaultValue = "normal")
	protected StyleStateEnumType key;
	@XmlSchemaType(name = "anyURI")
	protected String styleUrl;
	@XmlElementRef(name = "AbstractStyleSelectorGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<? extends AbstractStyleSelectorType> abstractStyleSelectorGroup;

	/**
	 * Gets the value of the key property.
	 * 
	 * @return possible object is {@link StyleStateEnumType }
	 * 
	 */
	public StyleStateEnumType getKey() {
		return key;
	}

	/**
	 * Sets the value of the key property.
	 * 
	 * @param value
	 *            allowed object is {@link StyleStateEnumType }
	 * 
	 */
	public void setKey(StyleStateEnumType value) {
		this.key = value;
	}

	/**
	 * Gets the value of the styleUrl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStyleUrl() {
		return styleUrl;
	}

	/**
	 * Sets the value of the styleUrl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStyleUrl(String value) {
		this.styleUrl = value;
	}

	/**
	 * Gets the value of the abstractStyleSelectorGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}
	 *         {@link AbstractStyleSelectorType }{@code >} {@link JAXBElement }
	 *         {@code <}{@link StyleMapType }{@code >} {@link JAXBElement }{@code
	 *         <}{@link StyleType }{@code >}
	 * 
	 */
	public JAXBElement<? extends AbstractStyleSelectorType> getAbstractStyleSelectorGroup() {
		return abstractStyleSelectorGroup;
	}

	/**
	 * Sets the value of the abstractStyleSelectorGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}
	 *            {@link AbstractStyleSelectorType }{@code >} {@link JAXBElement }
	 *            {@code <}{@link StyleMapType }{@code >} {@link JAXBElement }
	 *            {@code <}{@link StyleType }{@code >}
	 * 
	 */
	public void setAbstractStyleSelectorGroup(
			JAXBElement<? extends AbstractStyleSelectorType> value) {
		this.abstractStyleSelectorGroup = (value);
	}

}
