//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PhotoOverlayType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;PhotoOverlayType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractOverlayType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}rotation&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}ViewVolume&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}ImagePyramid&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Point&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}shape&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhotoOverlayType", propOrder = { "rotation", "viewVolume",
		"imagePyramid", "point", "shape" })
public class PhotoOverlayType extends AbstractOverlayType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7357314774432444659L;
	@XmlElement(defaultValue = "0.0")
	protected Double rotation;
	@XmlElement(name = "ViewVolume")
	protected ViewVolumeType viewVolume;
	@XmlElement(name = "ImagePyramid")
	protected ImagePyramidType imagePyramid;
	@XmlElement(name = "Point")
	protected PointType point;
	@XmlElement(defaultValue = "rectangle")
	protected ShapeEnumType shape;

	/**
	 * Gets the value of the rotation property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getRotation() {
		return rotation;
	}

	/**
	 * Sets the value of the rotation property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setRotation(Double value) {
		this.rotation = value;
	}

	/**
	 * Gets the value of the viewVolume property.
	 * 
	 * @return possible object is {@link ViewVolumeType }
	 * 
	 */
	public ViewVolumeType getViewVolume() {
		return viewVolume;
	}

	/**
	 * Sets the value of the viewVolume property.
	 * 
	 * @param value
	 *            allowed object is {@link ViewVolumeType }
	 * 
	 */
	public void setViewVolume(ViewVolumeType value) {
		this.viewVolume = value;
	}

	/**
	 * Gets the value of the imagePyramid property.
	 * 
	 * @return possible object is {@link ImagePyramidType }
	 * 
	 */
	public ImagePyramidType getImagePyramid() {
		return imagePyramid;
	}

	/**
	 * Sets the value of the imagePyramid property.
	 * 
	 * @param value
	 *            allowed object is {@link ImagePyramidType }
	 * 
	 */
	public void setImagePyramid(ImagePyramidType value) {
		this.imagePyramid = value;
	}

	/**
	 * Gets the value of the point property.
	 * 
	 * @return possible object is {@link PointType }
	 * 
	 */
	public PointType getPoint() {
		return point;
	}

	/**
	 * Sets the value of the point property.
	 * 
	 * @param value
	 *            allowed object is {@link PointType }
	 * 
	 */
	public void setPoint(PointType value) {
		this.point = value;
	}

	/**
	 * Gets the value of the shape property.
	 * 
	 * @return possible object is {@link ShapeEnumType }
	 * 
	 */
	public ShapeEnumType getShape() {
		return shape;
	}

	/**
	 * Sets the value of the shape property.
	 * 
	 * @param value
	 *            allowed object is {@link ShapeEnumType }
	 * 
	 */
	public void setShape(ShapeEnumType value) {
		this.shape = value;
	}

}
