//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PlacemarkType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;PlacemarkType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractFeatureType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}AbstractGeometryGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlacemarkType", propOrder = { "abstractGeometryGroup" })
public class PlacemarkType extends AbstractFeatureType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6346837806392122245L;
	@XmlElementRef(name = "AbstractGeometryGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<? extends AbstractGeometryType> abstractGeometryGroup;

	/**
	 * Gets the value of the abstractGeometryGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}
	 *         {@link LinearRingType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link LineStringType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link MultiGeometryType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link PointType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link AbstractGeometryType }{@code >} {@link JAXBElement }{@code
	 *         <}{@link PolygonType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link ModelType }{@code >}
	 * 
	 */
	public JAXBElement<? extends AbstractGeometryType> getAbstractGeometryGroup() {
		return abstractGeometryGroup;
	}

	/**
	 * Sets the value of the abstractGeometryGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}
	 *            {@link LinearRingType }{@code >} {@link JAXBElement }{@code <}
	 *            {@link LineStringType }{@code >} {@link JAXBElement }{@code <}
	 *            {@link MultiGeometryType }{@code >} {@link JAXBElement }{@code
	 *            <}{@link PointType }{@code >} {@link JAXBElement }{@code <}
	 *            {@link AbstractGeometryType }{@code >} {@link JAXBElement }
	 *            {@code <}{@link PolygonType }{@code >} {@link JAXBElement }
	 *            {@code <}{@link ModelType }{@code >}
	 * 
	 */
	public void setAbstractGeometryGroup(
			JAXBElement<? extends AbstractGeometryType> value) {
		this.abstractGeometryGroup = (value);
	}

}
