//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ScaleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ScaleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractObjectType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}x&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}y&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}z&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScaleType", propOrder = { "x", "y", "z" })
public class ScaleType extends AbstractObjectType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8610387006168329605L;
	@XmlElement(defaultValue = "1.0")
	protected Double x;
	@XmlElement(defaultValue = "1.0")
	protected Double y;
	@XmlElement(defaultValue = "1.0")
	protected Double z;

	/**
	 * Gets the value of the x property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getX() {
		return x;
	}

	/**
	 * Sets the value of the x property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setX(Double value) {
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getY() {
		return y;
	}

	/**
	 * Sets the value of the y property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setY(Double value) {
		this.y = value;
	}

	/**
	 * Gets the value of the z property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getZ() {
		return z;
	}

	/**
	 * Sets the value of the z property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setZ(Double value) {
		this.z = value;
	}

}
