//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TimeSpanType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;TimeSpanType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractTimePrimitiveType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}begin&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}end&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeSpanType", propOrder = { "begin", "end" })
public class TimeSpanType extends AbstractTimePrimitiveType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8176394122047021490L;
	protected String begin;
	protected String end;

	/**
	 * Gets the value of the begin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBegin() {
		return begin;
	}

	/**
	 * Sets the value of the begin property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBegin(String value) {
		this.begin = value;
	}

	/**
	 * Gets the value of the end property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEnd() {
		return end;
	}

	/**
	 * Sets the value of the end property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEnd(String value) {
		this.end = value;
	}

}
