//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for unitsEnumType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;unitsEnumType&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;fraction&quot;/&gt;
 *     &lt;enumeration value=&quot;pixels&quot;/&gt;
 *     &lt;enumeration value=&quot;insetPixels&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "unitsEnumType")
@XmlEnum
public enum UnitsEnumType implements java.io.Serializable {

	@XmlEnumValue("fraction")
	FRACTION("fraction"), @XmlEnumValue("pixels")
	PIXELS("pixels"), @XmlEnumValue("insetPixels")
	INSET_PIXELS("insetPixels");
	private final String value;

	UnitsEnumType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static UnitsEnumType fromValue(String v) {
		for (UnitsEnumType c : UnitsEnumType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
