//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for AbstractColorStyleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;AbstractColorStyleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractSubStyleType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}color&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}colorMode&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractColorStyleType", propOrder = { "color", "colorMode" })
@XmlSeeAlso( { IconStyleType.class, LabelStyleType.class, LineStyleType.class,
		PolyStyleType.class })
public abstract class AbstractColorStyleType extends AbstractSubStyleType
		implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8475305493929444158L;
	@XmlElement(type = String.class, defaultValue = "ffffffff")
	@XmlJavaTypeAdapter(HexBinaryAdapter.class)
	protected byte[] color;
	@XmlElement(defaultValue = "normal")
	protected ColorModeEnumType colorMode;

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public byte[] getColor() {
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(byte[] value) {
		this.color = (value);
	}

	/**
	 * Gets the value of the colorMode property.
	 * 
	 * @return possible object is {@link ColorModeEnumType }
	 * 
	 */
	public ColorModeEnumType getColorMode() {
		return colorMode;
	}

	/**
	 * Sets the value of the colorMode property.
	 * 
	 * @param value
	 *            allowed object is {@link ColorModeEnumType }
	 * 
	 */
	public void setColorMode(ColorModeEnumType value) {
		this.colorMode = value;
	}

}
