//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import cz.agents.alite.googleearth.oasis.AddressDetails;
import cz.agents.alite.googleearth.w3.AtomPersonConstruct;
import cz.agents.alite.googleearth.w3.Link;


/**
 * <p>
 * Java class for AbstractFeatureType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;AbstractFeatureType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractObjectType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}name&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}visibility&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}open&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://www.w3.org/2005/Atom}author&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://www.w3.org/2005/Atom}link&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}address&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{urn:oasis:names:tc:ciq:xsdschema:xAL:2.0}AddressDetails&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}phoneNumber&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Snippet&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}description&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}AbstractViewGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}AbstractTimePrimitiveGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}styleUrl&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}AbstractStyleSelectorGroup&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Region&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Metadata&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}ExtendedData&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractFeatureType", propOrder = { "name", "visibility",
		"open", "author", "link", "address", "addressDetails", "phoneNumber",
		"snippet", "description", "abstractViewGroup",
		"abstractTimePrimitiveGroup", "styleUrl", "abstractStyleSelectorGroup",
		"region", "metadata", "extendedData" })
@XmlSeeAlso( { NetworkLinkType.class, AbstractOverlayType.class,
		AbstractContainerType.class, PlacemarkType.class })
public abstract class AbstractFeatureType extends AbstractObjectType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3037112624260668111L;
	protected String name;
	@XmlElement(defaultValue = "1")
	protected Boolean visibility;
	@XmlElement(defaultValue = "0")
	protected Boolean open;
	@XmlElement(namespace = "http://www.w3.org/2005/Atom")
	protected AtomPersonConstruct author;
	@XmlElement(namespace = "http://www.w3.org/2005/Atom")
	protected Link link;
	protected String address;
	@XmlElement(name = "AddressDetails", namespace = "urn:oasis:names:tc:ciq:xsdschema:xAL:2.0")
	protected AddressDetails addressDetails;
	protected String phoneNumber;
	@XmlElement(name = "Snippet")
	protected SnippetType snippet;
	protected String description;
	@XmlElementRef(name = "AbstractViewGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<? extends AbstractViewType> abstractViewGroup;
	@XmlElementRef(name = "AbstractTimePrimitiveGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<? extends AbstractTimePrimitiveType> abstractTimePrimitiveGroup;
	@XmlSchemaType(name = "anyURI")
	protected String styleUrl;
	@XmlElementRef(name = "AbstractStyleSelectorGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected List<JAXBElement<? extends AbstractStyleSelectorType>> abstractStyleSelectorGroup;
	@XmlElement(name = "Region")
	protected RegionType region;
	@XmlElement(name = "Metadata")
	protected MetadataType metadata;
	@XmlElement(name = "ExtendedData")
	protected ExtendedDataType extendedData;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the visibility property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isVisibility() {
		return visibility;
	}

	/**
	 * Sets the value of the visibility property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setVisibility(Boolean value) {
		this.visibility = value;
	}

	/**
	 * Gets the value of the open property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isOpen() {
		return open;
	}

	/**
	 * Sets the value of the open property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOpen(Boolean value) {
		this.open = value;
	}

	/**
	 * Gets the value of the author property.
	 * 
	 * @return possible object is {@link AtomPersonConstruct }
	 * 
	 */
	public AtomPersonConstruct getAuthor() {
		return author;
	}

	/**
	 * Sets the value of the author property.
	 * 
	 * @param value
	 *            allowed object is {@link AtomPersonConstruct }
	 * 
	 */
	public void setAuthor(AtomPersonConstruct value) {
		this.author = value;
	}

	/**
	 * Gets the value of the link property.
	 * 
	 * @return possible object is {@link Link }
	 * 
	 */
	public Link getLink() {
		return link;
	}

	/**
	 * Sets the value of the link property.
	 * 
	 * @param value
	 *            allowed object is {@link Link }
	 * 
	 */
	public void setLink(Link value) {
		this.link = value;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAddress(String value) {
		this.address = value;
	}

	/**
	 * Gets the value of the addressDetails property.
	 * 
	 * @return possible object is {@link AddressDetails }
	 * 
	 */
	public AddressDetails getAddressDetails() {
		return addressDetails;
	}

	/**
	 * Sets the value of the addressDetails property.
	 * 
	 * @param value
	 *            allowed object is {@link AddressDetails }
	 * 
	 */
	public void setAddressDetails(AddressDetails value) {
		this.addressDetails = value;
	}

	/**
	 * Gets the value of the phoneNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * Sets the value of the phoneNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPhoneNumber(String value) {
		this.phoneNumber = value;
	}

	/**
	 * Gets the value of the snippet property.
	 * 
	 * @return possible object is {@link SnippetType }
	 * 
	 */
	public SnippetType getSnippet() {
		return snippet;
	}

	/**
	 * Sets the value of the snippet property.
	 * 
	 * @param value
	 *            allowed object is {@link SnippetType }
	 * 
	 */
	public void setSnippet(SnippetType value) {
		this.snippet = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the abstractViewGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}
	 *         {@link AbstractViewType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link CameraType }{@code >} {@link JAXBElement }{@code <}
	 *         {@link LookAtType }{@code >}
	 * 
	 */
	public JAXBElement<? extends AbstractViewType> getAbstractViewGroup() {
		return abstractViewGroup;
	}

	/**
	 * Sets the value of the abstractViewGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}
	 *            {@link AbstractViewType }{@code >} {@link JAXBElement }{@code <}
	 *            {@link CameraType }{@code >} {@link JAXBElement }{@code <}
	 *            {@link LookAtType }{@code >}
	 * 
	 */
	public void setAbstractViewGroup(
			JAXBElement<? extends AbstractViewType> value) {
		this.abstractViewGroup = (value);
	}

	/**
	 * Gets the value of the abstractTimePrimitiveGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}
	 *         {@link AbstractTimePrimitiveType }{@code >} {@link JAXBElement }
	 *         {@code <}{@link TimeStampType }{@code >} {@link JAXBElement }
	 *         {@code <}{@link TimeSpanType }{@code >}
	 * 
	 */
	public JAXBElement<? extends AbstractTimePrimitiveType> getAbstractTimePrimitiveGroup() {
		return abstractTimePrimitiveGroup;
	}

	/**
	 * Sets the value of the abstractTimePrimitiveGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}
	 *            {@link AbstractTimePrimitiveType }{@code >} {@link JAXBElement }
	 *            {@code <}{@link TimeStampType }{@code >} {@link JAXBElement }
	 *            {@code <}{@link TimeSpanType }{@code >}
	 * 
	 */
	public void setAbstractTimePrimitiveGroup(
			JAXBElement<? extends AbstractTimePrimitiveType> value) {
		this.abstractTimePrimitiveGroup = (value);
	}

	/**
	 * Gets the value of the styleUrl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStyleUrl() {
		return styleUrl;
	}

	/**
	 * Sets the value of the styleUrl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStyleUrl(String value) {
		this.styleUrl = value;
	}

	/**
	 * Gets the value of the abstractStyleSelectorGroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the abstractStyleSelectorGroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAbstractStyleSelectorGroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link AbstractStyleSelectorType }{@code >}
	 * {@link JAXBElement }{@code <}{@link StyleMapType }{@code >}
	 * {@link JAXBElement }{@code <}{@link StyleType }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<? extends AbstractStyleSelectorType>> getAbstractStyleSelectorGroup() {
		if (abstractStyleSelectorGroup == null) {
			abstractStyleSelectorGroup = new ArrayList<JAXBElement<? extends AbstractStyleSelectorType>>();
		}
		return this.abstractStyleSelectorGroup;
	}

	/**
	 * Gets the value of the region property.
	 * 
	 * @return possible object is {@link RegionType }
	 * 
	 */
	public RegionType getRegion() {
		return region;
	}

	/**
	 * Sets the value of the region property.
	 * 
	 * @param value
	 *            allowed object is {@link RegionType }
	 * 
	 */
	public void setRegion(RegionType value) {
		this.region = value;
	}

	/**
	 * Gets the value of the metadata property.
	 * 
	 * @return possible object is {@link MetadataType }
	 * 
	 */
	public MetadataType getMetadata() {
		return metadata;
	}

	/**
	 * Sets the value of the metadata property.
	 * 
	 * @param value
	 *            allowed object is {@link MetadataType }
	 * 
	 */
	public void setMetadata(MetadataType value) {
		this.metadata = value;
	}

	/**
	 * Gets the value of the extendedData property.
	 * 
	 * @return possible object is {@link ExtendedDataType }
	 * 
	 */
	public ExtendedDataType getExtendedData() {
		return extendedData;
	}

	/**
	 * Sets the value of the extendedData property.
	 * 
	 * @param value
	 *            allowed object is {@link ExtendedDataType }
	 * 
	 */
	public void setExtendedData(ExtendedDataType value) {
		this.extendedData = value;
	}

}
