//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ImagePyramidType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ImagePyramidType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractObjectType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}tileSize&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}maxWidth&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}maxHeight&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}gridOrigin&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImagePyramidType", propOrder = { "tileSize", "maxWidth",
		"maxHeight", "gridOrigin" })
public class ImagePyramidType extends AbstractObjectType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3446009143761565490L;
	@XmlElement(defaultValue = "256")
	protected Integer tileSize;
	@XmlElement(defaultValue = "0")
	protected Integer maxWidth;
	@XmlElement(defaultValue = "0")
	protected Integer maxHeight;
	@XmlElement(defaultValue = "lowerLeft")
	protected GridOriginEnumType gridOrigin;

	/**
	 * Gets the value of the tileSize property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getTileSize() {
		return tileSize;
	}

	/**
	 * Sets the value of the tileSize property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setTileSize(Integer value) {
		this.tileSize = value;
	}

	/**
	 * Gets the value of the maxWidth property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getMaxWidth() {
		return maxWidth;
	}

	/**
	 * Sets the value of the maxWidth property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setMaxWidth(Integer value) {
		this.maxWidth = value;
	}

	/**
	 * Gets the value of the maxHeight property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getMaxHeight() {
		return maxHeight;
	}

	/**
	 * Sets the value of the maxHeight property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setMaxHeight(Integer value) {
		this.maxHeight = value;
	}

	/**
	 * Gets the value of the gridOrigin property.
	 * 
	 * @return possible object is {@link GridOriginEnumType }
	 * 
	 */
	public GridOriginEnumType getGridOrigin() {
		return gridOrigin;
	}

	/**
	 * Sets the value of the gridOrigin property.
	 * 
	 * @param value
	 *            allowed object is {@link GridOriginEnumType }
	 * 
	 */
	public void setGridOrigin(GridOriginEnumType value) {
		this.gridOrigin = value;
	}

}
