//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LookAtType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;LookAtType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractViewType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}longitude&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}latitude&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}altitude&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}heading&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}tilt&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}range&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}altitudeModeGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LookAtType", propOrder = { "longitude", "latitude",
		"altitude", "heading", "tilt", "range", "altitudeModeGroup" })
public class LookAtType extends AbstractViewType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8239840146890343966L;
	@XmlElement(defaultValue = "0.0")
	protected Double longitude;
	@XmlElement(defaultValue = "0.0")
	protected Double latitude;
	@XmlElement(defaultValue = "0.0")
	protected Double altitude;
	@XmlElement(defaultValue = "0.0")
	protected Double heading;
	@XmlElement(defaultValue = "0.0")
	protected Double tilt;
	@XmlElement(defaultValue = "0.0")
	protected Double range;
	@XmlElementRef(name = "altitudeModeGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<?> altitudeModeGroup;

	/**
	 * Gets the value of the longitude property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getLongitude() {
		return longitude;
	}

	/**
	 * Sets the value of the longitude property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setLongitude(Double value) {
		this.longitude = value;
	}

	/**
	 * Gets the value of the latitude property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getLatitude() {
		return latitude;
	}

	/**
	 * Sets the value of the latitude property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setLatitude(Double value) {
		this.latitude = value;
	}

	/**
	 * Gets the value of the altitude property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getAltitude() {
		return altitude;
	}

	/**
	 * Sets the value of the altitude property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setAltitude(Double value) {
		this.altitude = value;
	}

	/**
	 * Gets the value of the heading property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getHeading() {
		return heading;
	}

	/**
	 * Sets the value of the heading property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setHeading(Double value) {
		this.heading = value;
	}

	/**
	 * Gets the value of the tilt property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getTilt() {
		return tilt;
	}

	/**
	 * Sets the value of the tilt property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setTilt(Double value) {
		this.tilt = value;
	}

	/**
	 * Gets the value of the range property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getRange() {
		return range;
	}

	/**
	 * Sets the value of the range property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setRange(Double value) {
		this.range = value;
	}

	/**
	 * Gets the value of the altitudeModeGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link Object }
	 *         {@code >} {@link JAXBElement }{@code <}
	 *         {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public JAXBElement<?> getAltitudeModeGroup() {
		return altitudeModeGroup;
	}

	/**
	 * Sets the value of the altitudeModeGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Object }
	 *            {@code >} {@link JAXBElement }{@code <}
	 *            {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public void setAltitudeModeGroup(JAXBElement<?> value) {
		this.altitudeModeGroup = (value);
	}

}
