//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for NetworkLinkType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;NetworkLinkType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractFeatureType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}refreshVisibility&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}flyToView&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;choice minOccurs=&quot;0&quot;&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Link&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Url&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkLinkType", propOrder = { "rest" })
public class NetworkLinkType extends AbstractFeatureType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3106706108133584774L;
	@XmlElementRefs( {
			@XmlElementRef(name = "refreshVisibility", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class),
			@XmlElementRef(name = "Link", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class),
			@XmlElementRef(name = "flyToView", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class),
			@XmlElementRef(name = "Url", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class) })
	protected List<JAXBElement<?>> rest;

	/**
	 * Gets the rest of the content model.
	 * 
	 * <p>
	 * You are getting this "catch-all" property because of the following
	 * reason: The field name "Link" is used by two different parts of a schema.
	 * See: line 619 of
	 * file:/C:/petr/2009_ls/google_maps/kml/schema/kkk/kml22beta.xsd line 340
	 * of file:/C:/petr/2009_ls/google_maps/kml/schema/kkk/kml22beta.xsd
	 * <p>
	 * To get rid of this property, apply a property customization to one of
	 * both of the following declarations to change their names: Gets the value
	 * of the rest property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the rest property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRest().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link LinkType }{@code >} {@link JAXBElement }
	 * {@code <}{@link Boolean }{@code >} {@link JAXBElement }{@code <}
	 * {@link LinkType }{@code >} {@link JAXBElement }{@code <}{@link Boolean }
	 * {@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<?>> getRest() {
		if (rest == null) {
			rest = new ArrayList<JAXBElement<?>>();
		}
		return this.rest;
	}

}
