//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PointType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;PointType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractGeometryType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}extrude&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}altitudeModeGroup&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}coordinates&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointType", propOrder = { "extrude", "altitudeModeGroup",
		"coordinates" })
public class PointType extends AbstractGeometryType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4291953304152153899L;
	@XmlElement(defaultValue = "0")
	protected Boolean extrude;
	@XmlElementRef(name = "altitudeModeGroup", namespace = "http://earth.google.com/kml/2.2", type = JAXBElement.class)
	protected JAXBElement<?> altitudeModeGroup;
	@XmlList
	protected List<String> coordinates;

	/**
	 * Gets the value of the extrude property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isExtrude() {
		return extrude;
	}

	/**
	 * Sets the value of the extrude property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setExtrude(Boolean value) {
		this.extrude = value;
	}

	/**
	 * Gets the value of the altitudeModeGroup property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link Object }
	 *         {@code >} {@link JAXBElement }{@code <}
	 *         {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public JAXBElement<?> getAltitudeModeGroup() {
		return altitudeModeGroup;
	}

	/**
	 * Sets the value of the altitudeModeGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Object }
	 *            {@code >} {@link JAXBElement }{@code <}
	 *            {@link AltitudeModeEnumType }{@code >}
	 * 
	 */
	public void setAltitudeModeGroup(JAXBElement<?> value) {
		this.altitudeModeGroup = (value);
	}

	/**
	 * Gets the value of the coordinates property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the coordinates property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCoordinates().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getCoordinates() {
		if (coordinates == null) {
			coordinates = new ArrayList<String>();
		}
		return this.coordinates;
	}

}
