//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PolyStyleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;PolyStyleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractColorStyleType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}fill&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}outline&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolyStyleType", propOrder = { "fill", "outline" })
public class PolyStyleType extends AbstractColorStyleType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3457102218526552196L;
	@XmlElement(defaultValue = "1")
	protected Boolean fill;
	@XmlElement(defaultValue = "1")
	protected Boolean outline;

	/**
	 * Gets the value of the fill property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isFill() {
		return fill;
	}

	/**
	 * Sets the value of the fill property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setFill(Boolean value) {
		this.fill = value;
	}

	/**
	 * Gets the value of the outline property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isOutline() {
		return outline;
	}

	/**
	 * Sets the value of the outline property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOutline(Boolean value) {
		this.outline = value;
	}

}
