//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for refreshModeEnumType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;refreshModeEnumType&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;onChange&quot;/&gt;
 *     &lt;enumeration value=&quot;onInterval&quot;/&gt;
 *     &lt;enumeration value=&quot;onExpire&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "refreshModeEnumType")
@XmlEnum
public enum RefreshModeEnumType implements java.io.Serializable {

	@XmlEnumValue("onChange")
	ON_CHANGE("onChange"), @XmlEnumValue("onInterval")
	ON_INTERVAL("onInterval"), @XmlEnumValue("onExpire")
	ON_EXPIRE("onExpire");
	private final String value;

	RefreshModeEnumType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static RefreshModeEnumType fromValue(String v) {
		for (RefreshModeEnumType c : RefreshModeEnumType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
