//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ScreenOverlayType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ScreenOverlayType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.2}AbstractOverlayType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}overlayXY&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}screenXY&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}rotationXY&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}size&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}rotation&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScreenOverlayType", propOrder = { "overlayXY", "screenXY",
		"rotationXY", "size", "rotation" })
public class ScreenOverlayType extends AbstractOverlayType implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2096240506206077221L;
	protected Vec2Type overlayXY;
	protected Vec2Type screenXY;
	protected Vec2Type rotationXY;
	protected Vec2Type size;
	@XmlElement(defaultValue = "0.0")
	protected Double rotation;

	/**
	 * Gets the value of the overlayXY property.
	 * 
	 * @return possible object is {@link Vec2Type }
	 * 
	 */
	public Vec2Type getOverlayXY() {
		return overlayXY;
	}

	/**
	 * Sets the value of the overlayXY property.
	 * 
	 * @param value
	 *            allowed object is {@link Vec2Type }
	 * 
	 */
	public void setOverlayXY(Vec2Type value) {
		this.overlayXY = value;
	}

	/**
	 * Gets the value of the screenXY property.
	 * 
	 * @return possible object is {@link Vec2Type }
	 * 
	 */
	public Vec2Type getScreenXY() {
		return screenXY;
	}

	/**
	 * Sets the value of the screenXY property.
	 * 
	 * @param value
	 *            allowed object is {@link Vec2Type }
	 * 
	 */
	public void setScreenXY(Vec2Type value) {
		this.screenXY = value;
	}

	/**
	 * Gets the value of the rotationXY property.
	 * 
	 * @return possible object is {@link Vec2Type }
	 * 
	 */
	public Vec2Type getRotationXY() {
		return rotationXY;
	}

	/**
	 * Sets the value of the rotationXY property.
	 * 
	 * @param value
	 *            allowed object is {@link Vec2Type }
	 * 
	 */
	public void setRotationXY(Vec2Type value) {
		this.rotationXY = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link Vec2Type }
	 * 
	 */
	public Vec2Type getSize() {
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link Vec2Type }
	 * 
	 */
	public void setSize(Vec2Type value) {
		this.size = value;
	}

	/**
	 * Gets the value of the rotation property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getRotation() {
		return rotation;
	}

	/**
	 * Sets the value of the rotation property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setRotation(Double value) {
		this.rotation = value;
	}

}
