//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for UpdateType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;UpdateType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.2}targetHref&quot;/&gt;
 *         &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Create&quot;/&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Delete&quot;/&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.2}Change&quot;/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateType", propOrder = { "targetHref",
		"createOrDeleteOrChange" })
public class UpdateType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8745489942160565915L;
	@XmlElement(required = true)
	@XmlSchemaType(name = "anyURI")
	protected String targetHref;
	@XmlElements( { @XmlElement(name = "Create", type = CreateType.class),
			@XmlElement(name = "Delete", type = DeleteType.class),
			@XmlElement(name = "Change", type = ChangeType.class) })
	protected List<Object> createOrDeleteOrChange;

	/**
	 * Gets the value of the targetHref property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTargetHref() {
		return targetHref;
	}

	/**
	 * Sets the value of the targetHref property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTargetHref(String value) {
		this.targetHref = value;
	}

	/**
	 * Gets the value of the createOrDeleteOrChange property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the createOrDeleteOrChange property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCreateOrDeleteOrChange().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CreateType } {@link DeleteType } {@link ChangeType }
	 * 
	 * 
	 */
	public List<Object> getCreateOrDeleteOrChange() {
		if (createOrDeleteOrChange == null) {
			createOrDeleteOrChange = new ArrayList<Object>();
		}
		return this.createOrDeleteOrChange;
	}

}
