//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.kml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for vec2Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;vec2Type&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;attribute name=&quot;x&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot; default=&quot;1.0&quot; /&gt;
 *       &lt;attribute name=&quot;y&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot; default=&quot;1.0&quot; /&gt;
 *       &lt;attribute name=&quot;xunits&quot; type=&quot;{http://earth.google.com/kml/2.2}unitsEnumType&quot; default=&quot;fraction&quot; /&gt;
 *       &lt;attribute name=&quot;yunits&quot; type=&quot;{http://earth.google.com/kml/2.2}unitsEnumType&quot; default=&quot;fraction&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vec2Type")
public class Vec2Type implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6243445391317552272L;
	@XmlAttribute
	protected Double x;
	@XmlAttribute
	protected Double y;
	@XmlAttribute
	protected UnitsEnumType xunits;
	@XmlAttribute
	protected UnitsEnumType yunits;

	/**
	 * Gets the value of the x property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public double getX() {
		if (x == null) {
			return 1.0D;
		} else {
			return x;
		}
	}

	/**
	 * Sets the value of the x property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setX(Double value) {
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public double getY() {
		if (y == null) {
			return 1.0D;
		} else {
			return y;
		}
	}

	/**
	 * Sets the value of the y property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setY(Double value) {
		this.y = value;
	}

	/**
	 * Gets the value of the xunits property.
	 * 
	 * @return possible object is {@link UnitsEnumType }
	 * 
	 */
	public UnitsEnumType getXunits() {
		if (xunits == null) {
			return UnitsEnumType.FRACTION;
		} else {
			return xunits;
		}
	}

	/**
	 * Sets the value of the xunits property.
	 * 
	 * @param value
	 *            allowed object is {@link UnitsEnumType }
	 * 
	 */
	public void setXunits(UnitsEnumType value) {
		this.xunits = value;
	}

	/**
	 * Gets the value of the yunits property.
	 * 
	 * @return possible object is {@link UnitsEnumType }
	 * 
	 */
	public UnitsEnumType getYunits() {
		if (yunits == null) {
			return UnitsEnumType.FRACTION;
		} else {
			return yunits;
		}
	}

	/**
	 * Sets the value of the yunits property.
	 * 
	 * @param value
	 *            allowed object is {@link UnitsEnumType }
	 * 
	 */
	public void setYunits(UnitsEnumType value) {
		this.yunits = value;
	}

}
