//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.oasis;

import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;attGroup ref=&quot;{urn:oasis:names:tc:ciq:xsdschema:xAL:2.0}grPostal&quot;/&gt;
 *       &lt;attribute name=&quot;NumberType&quot;&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}NMTOKEN&quot;&gt;
 *             &lt;enumeration value=&quot;Single&quot;/&gt;
 *             &lt;enumeration value=&quot;Range&quot;/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name=&quot;Type&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *       &lt;attribute name=&quot;Indicator&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *       &lt;attribute name=&quot;IndicatorOccurrence&quot;&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}NMTOKEN&quot;&gt;
 *             &lt;enumeration value=&quot;Before&quot;/&gt;
 *             &lt;enumeration value=&quot;After&quot;/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name=&quot;NumberOccurrence&quot;&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}NMTOKEN&quot;&gt;
 *             &lt;enumeration value=&quot;BeforeName&quot;/&gt;
 *             &lt;enumeration value=&quot;AfterName&quot;/&gt;
 *             &lt;enumeration value=&quot;BeforeType&quot;/&gt;
 *             &lt;enumeration value=&quot;AfterType&quot;/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "content" })
@XmlRootElement(name = "ThoroughfareNumber")
public class ThoroughfareNumber implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3527195530882450214L;
	@XmlValue
	protected String content;
	@XmlAttribute(name = "NumberType")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String numberType;
	@XmlAttribute(name = "Type")
	@XmlSchemaType(name = "anySimpleType")
	protected String type;
	@XmlAttribute(name = "Indicator")
	@XmlSchemaType(name = "anySimpleType")
	protected String indicator;
	@XmlAttribute(name = "IndicatorOccurrence")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String indicatorOccurrence;
	@XmlAttribute(name = "NumberOccurrence")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String numberOccurrence;
	@XmlAttribute(name = "Code")
	@XmlSchemaType(name = "anySimpleType")
	protected String code;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the content property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContent() {
		return content;
	}

	/**
	 * Sets the value of the content property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContent(String value) {
		this.content = value;
	}

	/**
	 * Gets the value of the numberType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumberType() {
		return numberType;
	}

	/**
	 * Sets the value of the numberType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumberType(String value) {
		this.numberType = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the indicator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIndicator() {
		return indicator;
	}

	/**
	 * Sets the value of the indicator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIndicator(String value) {
		this.indicator = value;
	}

	/**
	 * Gets the value of the indicatorOccurrence property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIndicatorOccurrence() {
		return indicatorOccurrence;
	}

	/**
	 * Sets the value of the indicatorOccurrence property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIndicatorOccurrence(String value) {
		this.indicatorOccurrence = value;
	}

	/**
	 * Gets the value of the numberOccurrence property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumberOccurrence() {
		return numberOccurrence;
	}

	/**
	 * Sets the value of the numberOccurrence property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumberOccurrence(String value) {
		this.numberOccurrence = value;
	}

	/**
	 * Gets the value of the code property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCode() {
		return code;
	}

	/**
	 * Sets the value of the code property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCode(String value) {
		this.code = value;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed
	 * property on this class.
	 * 
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 * 
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 * 
	 * 
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

}
