//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.11 at 05:27:40 odp. CET 
//

package cz.agents.alite.googleearth.w3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;attribute name=&quot;href&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *       &lt;attribute name=&quot;rel&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *       &lt;attribute name=&quot;type&quot; type=&quot;{http://www.w3.org/2005/Atom}atomMediaType&quot; /&gt;
 *       &lt;attribute name=&quot;hreflang&quot; type=&quot;{http://www.w3.org/2005/Atom}atomLanguageTag&quot; /&gt;
 *       &lt;attribute name=&quot;title&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *       &lt;attribute name=&quot;length&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anySimpleType&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "link")
public class Link implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5097213387817326446L;
	@XmlAttribute(required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String href;
	@XmlAttribute
	@XmlSchemaType(name = "anySimpleType")
	protected String rel;
	@XmlAttribute
	protected String type;
	@XmlAttribute
	protected String hreflang;
	@XmlAttribute
	@XmlSchemaType(name = "anySimpleType")
	protected String title;
	@XmlAttribute
	@XmlSchemaType(name = "anySimpleType")
	protected String length;

	/**
	 * Gets the value of the href property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHref() {
		return href;
	}

	/**
	 * Sets the value of the href property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHref(String value) {
		this.href = value;
	}

	/**
	 * Gets the value of the rel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRel() {
		return rel;
	}

	/**
	 * Sets the value of the rel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRel(String value) {
		this.rel = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the hreflang property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHreflang() {
		return hreflang;
	}

	/**
	 * Sets the value of the hreflang property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHreflang(String value) {
		this.hreflang = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the length property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLength() {
		return length;
	}

	/**
	 * Sets the value of the length property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLength(String value) {
		this.length = value;
	}

}
